FROM openjdk:11-jdk-alpine

WORKDIR /app
COPY target/DockerAssignment-0.0.1-SNAPSHOT.jar /app/DockerAssignment-0.0.1-SNAPSHOT.jar
EXPOSE 8082
CMD ["java", "-jar", "DockerAssignment-0.0.1-SNAPSHOT.jar"]
